### ISSUE TITLE
Fala Vini, dados interessantes !

### ISSUE THREAD

**Issue by massudy** [Viniciusbz/Data-Science-Testing#1]
me diz em qual database você quer ou posso criar um .js que vc executa pelo terminal e retorna esses dados em JSON, tenho uns dados legais pra você brincar rsrs

todavia, a melhor maneira é você usar o pacote do mongodb pra python pra consumir mongodb, ai eu te passo a conexão com a database, ou se preferir vc me passa uma conexão e eu jogo todos os dados pra sua database

abraço

**Comment by Viniciusbz** [comment]
Fala, Massud. Meu amigo estou apenas fazendo uns testes com o github codespaces utilizando datasets comuns mesmo.
